### PR TITLE
Bug 1291259 - change remote of gaia & gecko in base.xml r=gerard-majax

### PR DESCRIPTION
**Pull request by kskarthik**

### CODE REVIEW

**Comment by tdz** [comment]
I can r+ this, but you should pull into 'master', instead of 'cm-12.1-YOG7D'

**Comment by tdz** [comment]
Sorry, my fault. master already has this change.

**Comment by kskarthik** [comment]
@tdz not this master. Shall i do this commit on master ?

**Comment by tdz** [comment]
Please ignore my comments. I confused the repos.

**Pull request closed without merging**
